Repository codeit-8-Sprint-Part2-Project/Rolling, pull requests merged in 2024-07, with the labels that each got.

#10 [2024.07.15] postThemePage 1차 완성
  package-lock.json
  package.json
  src/App.tsx
  src/DTO/recipient/Recipient.ts
  src/index.css
  src/pages/postTheme/PostTheme.tsx
  src/pages/postTheme/api/ThemeProvider.tsx
  src/pages/postTheme/api/themeApi.ts
  src/pages/postTheme/assets/icons/ic_check_theme.png
  src/pages/postTheme/assets/icons/ic_plus_darkGray.png
  src/pages/postTheme/components/BackgroundColorList.tsx
  src/pages/postTheme/components/BackgroundImageList.tsx
  src/pages/postTheme/components/Form.tsx
  src/pages/postTheme/components/ReceiverInput.tsx
  src/pages/postTheme/components/ThemeSelection.tsx
  src/pages/postTheme/constants/enum.ts
  src/pages/postTheme/constants/images.d.ts
  src/pages/postTheme/constants/propTypes.ts
  src/pages/postTheme/hooks/useSubmitData.tsx
  src/pages/postTheme/hooks/useThemeContext.tsx
  src/pages/postTheme/hooks/useUpdateThemeData.tsx
  src/pages/postTheme/utils/getColorClass.tsx
  tailwind.config.js
Labels: Feat, Chore, Design, Rename

#14 [2024.07.16] PostEdit 페이지 구현 / 디렉토리 정리
  .gitignore
  package-lock.json
  src/App.tsx
  src/assets/icons/deleted.svg
  src/assets/icons/plus.svg
  src/pages/PostPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/api/api.tsx
  src/pages/PostPage/components/LazyLoading.tsx
  src/pages/PostPage/components/MessageCard.tsx
  src/pages/PostPage/components/MessageCardList.tsx
  src/pages/PostPage/components/MessageModal.tsx
  src/pages/PostPage/components/PlusCard.tsx
  src/pages/PostPage/components/Posts.tsx
  src/pages/PostPage/components/PostsHeader.tsx
  src/pages/PostPage/components/RelationshipLabel.tsx
  src/pages/PostPage/components/SenderInfo.tsx
  src/pages/PostPage/components/TrashcanButton.tsx
  src/pages/PostPage/utils/compareTime.js
  src/pages/PostPage/utils/formatComparedTime.js
  src/typings/images.d.ts
Labels: Feat, Chore

#15 postTheme: 이미지 업로드 기능 삭제, 기본 이미지 선택 기능 추가
  package-lock.json
  package.json
  src/pages/postTheme/PostTheme.tsx
  src/pages/postTheme/components/BackgroundColorList.tsx
  src/pages/postTheme/components/BackgroundImageList.tsx
  src/pages/postTheme/components/Form.tsx
  src/pages/postTheme/components/ReceiverInput.tsx
  src/pages/postTheme/components/ThemeSelection.tsx
  tailwind.config.js
Labels: Feat, Refactor

#18 [2024.07.17] PostNav api & style 완성 (+추가 emoji button, share button)
  package-lock.json
  package.json
  postcss.config.js
  public/assets/icons/IconColor.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/Nav.tsx
  src/components/UI/NavButton.tsx
  src/components/UI/NavContainer.tsx
  src/components/UI/NavLogo.tsx
  src/index.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/assets/images/HomepageTitle1.png
  src/pages/HomePage/assets/images/HomepageTitle2.png
  src/pages/HomePage/components/Layout/HomepageMain.tsx
  src/pages/HomePage/components/UI/BodyContainer.tsx
  src/pages/HomePage/components/UI/MainContainer.tsx
  src/pages/HomePage/components/UI/TitleButton.tsx
  src/pages/HomePage/components/UI/TitleContainer.tsx
  src/pages/HomePage/components/UI/TitleContents.tsx
  src/pages/HomePage/components/UI/TitleHeadContents.tsx
  src/pages/HomePage/components/UI/TitlePoint.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/api/getByPostId.tsx
  src/pages/PostPage/assets/icons/IconArrowDown.png
  src/pages/PostPage/assets/icons/IconEmojiAdd.png
  src/pages/PostPage/assets/icons/IconShare.png
  src/pages/PostPage/assets/icons/IconUrlClose.png
  src/pages/PostPage/assets/icons/IconUrlCompleted.png
  src/pages/PostPage/components/Layout/PostNav.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/PostNavContainer.tsx
  src/pages/PostPage/components/UI/PostNavTitleContainer.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
  src/reportWebVitals.ts
  src/typings/images.d.ts
  tailwind.config.js
Labels: Feat, Design

#21 postTheme: 커스텀 훅 생성, 리펙토링 작업
  src/pages/postTheme/PostTheme.tsx
  src/pages/postTheme/UI/CreateButton.tsx
  src/pages/postTheme/UI/ThemeCheckIc.tsx
  src/pages/postTheme/UI/ThemeTypeButton.tsx
  src/pages/postTheme/api/ThemeProvider.tsx
  src/pages/postTheme/api/getRecipients.ts
  src/pages/postTheme/components/BackgroundColorList.tsx
  src/pages/postTheme/components/BackgroundImageList.tsx
  src/pages/postTheme/components/ReceiverInput.tsx
  src/pages/postTheme/components/ThemeForm.tsx
  src/pages/postTheme/components/ThemeSelection.tsx
  src/pages/postTheme/constants/enum.ts
  src/pages/postTheme/constants/initial.ts
  src/pages/postTheme/constants/propTypes.ts
  src/pages/postTheme/hooks/useFetchThemeData.tsx
  src/pages/postTheme/hooks/useFetchUrls.tsx
  src/pages/postTheme/hooks/useSelectedTheme.tsx
  src/pages/postTheme/hooks/useSubmitData.tsx
  src/pages/postTheme/hooks/useThemeContext.tsx
  src/pages/postTheme/hooks/useThemeHandlers.tsx
Labels: Refactor

#22 [2024.07.17] design: 수정 버튼 추가
  src/pages/PostPage/PostEditPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/api/api.tsx
  src/pages/PostPage/components/DeletionConfirmModal.tsx
  src/pages/PostPage/components/MessageCard.tsx
  src/pages/PostPage/components/MessageCardList.tsx
  src/pages/PostPage/components/MessageModal.tsx
  src/pages/PostPage/components/Posts.tsx
  src/pages/PostPage/components/RecipientDeleteCard.tsx
  src/pages/PostPage/components/TrashcanButton.tsx
  src/pages/PostPage/utils/formatComparedTime.js
Labels: Design

#23 [2024.07.18] list: 최신 sender 3명의 프로필 이미지 보여주는 기능 추가
  src/pages/ListPage/components/BestRecipientCardList.tsx
  src/pages/ListPage/components/RecipientCard.tsx
  src/pages/ListPage/components/RecipientCardList.tsx
Labels: Feat, Design

#25 [2024.07.18] feat: "목록으로" 버튼 추가
  src/pages/PostPage/components/DeletionConfirmModal.tsx
  src/pages/PostPage/components/LazyLoading.tsx
  src/pages/PostPage/components/MainSectionButtons.tsx
  src/pages/PostPage/components/MessageModal.tsx
  src/pages/PostPage/components/Posts.tsx
Labels: Feat

#26 postTheme: 데이터 호출 오류 수정
  src/pages/postTheme/PostTheme.tsx
  src/pages/postTheme/api/ThemeProvider.tsx
  src/pages/postTheme/hooks/useGetThemeData.tsx
Labels: Fix

#27 [2024.07.18] POST NAV 카카오톡 공유하기 & 전역적인 Header
  .gitignore
  public/index.html
  src/App.tsx
  src/DTO/reaction/ReactionCreate.ts
  src/components/Layout/Header.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ListPage/ListPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/postTheme/PostTheme.tsx
  src/typings/kakao.d.ts
Labels: Feat

#29 [2024.07.18] list 카드 배경 이미지가 있을 시 어두워지도록 수정 & 프로필 이미지 옆에 카운트 넘버 추가
  src/pages/ListPage/components/RecipientCard.tsx
  src/pages/ListPage/components/RecipientCardList.tsx
Labels: Feat, Design

#31 postTheme: 선택한 테마 미리보기 기능
  package-lock.json
  package.json
  public/aseet/icons/IconColor.png
  src/pages/postTheme/PostTheme.tsx
  src/pages/postTheme/UI/PreviewPlusCard.tsx
  src/pages/postTheme/components/BackgroundColorList.tsx
  src/pages/postTheme/components/BackgroundImageList.tsx
  src/pages/postTheme/components/ThemePreview.tsx
  src/pages/postTheme/components/ThemeTypeSelection.tsx
  src/pages/postTheme/constants/propTypes.ts
  src/pages/postTheme/hooks/useDeleteData.tsx
  src/pages/postTheme/hooks/useGetUrls.tsx
  src/pages/postTheme/hooks/useSelectedTheme.tsx
Labels: Feat, Design

#32 Develop: 모달, 텍스트에디터 패키지 설치
  package-lock.json
  package.json
Labels: Chore

#34 [2024.07.18] 홈페이지 & post nav 반응형 구현
  src/components/Layout/Header.tsx
  src/components/Layout/Nav.tsx
  src/components/UI/NavContainer.tsx
  src/pages/HomePage/components/Layout/HomepageMain.tsx
  src/pages/HomePage/components/UI/BodyContainer.tsx
  src/pages/HomePage/components/UI/MainContainer.tsx
  src/pages/HomePage/components/UI/TitleButton.tsx
  src/pages/HomePage/components/UI/TitleContainer.tsx
  src/pages/PostPage/components/Layout/PostNav.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/PostNavContainer.tsx
  src/pages/PostPage/components/UI/PostNavTitleContainer.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
  tailwind.config.js
Labels: Style

#36 [2024.07.18] Rename : productid recipientId로 일괄변경
  src/pages/ListPage/api/getRecipient.tsx
  src/pages/PostPage/api/getByPostId.tsx
  src/pages/PostPage/api/getByReactions.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
Labels: Rename

#37 postCreate: postTheme -> postCreate 네이밍, 모달창 폰트 적용
  src/App.tsx
  src/pages/postCreatePage/PostCreate.tsx
  src/pages/postCreatePage/api/ThemeProvider.tsx
  src/pages/postCreatePage/api/getRecipients.ts
  src/pages/postCreatePage/assets/icons/ic_check_theme.png
  src/pages/postCreatePage/assets/icons/ic_plus_darkGray.png
  src/pages/postCreatePage/components/BackgroundColorList.tsx
  src/pages/postCreatePage/components/BackgroundImageList.tsx
  src/pages/postCreatePage/components/ReceiverInput.tsx
  src/pages/postCreatePage/components/ThemeForm.tsx
  src/pages/postCreatePage/components/ThemePreview.tsx
  src/pages/postCreatePage/components/ThemeTypeSelection.tsx
  src/pages/postCreatePage/components/UI/CreateButton.tsx
  src/pages/postCreatePage/components/UI/PreviewPlusCard.tsx
  src/pages/postCreatePage/components/UI/ThemeCheckIc.tsx
  src/pages/postCreatePage/components/UI/ThemeTypeButton.tsx
  src/pages/postCreatePage/constants/images.d.ts
  src/pages/postCreatePage/constants/initial.ts
  src/pages/postCreatePage/constants/propTypes.ts
  src/pages/postCreatePage/hooks/useDeleteData.tsx
  src/pages/postCreatePage/hooks/useGetUrls.tsx
  src/pages/postCreatePage/hooks/useSelectedTheme.tsx
  src/pages/postCreatePage/hooks/useSubmitData.tsx
  src/pages/postCreatePage/hooks/useThemeContext.tsx
  src/pages/postCreatePage/hooks/useThemeHandlers.tsx
  src/pages/postCreatePage/hooks/useUpdateThemeData.tsx
  src/pages/postCreatePage/utils/getColorClass.tsx
  src/pages/postTheme/constants/enum.ts
Labels: Design, Rename

#35 [2024.07.18] list 카드 리스트 반응형 구현
  package-lock.json
  package.json
  src/components/UI/Button.tsx
  src/pages/ListPage/api/getRecipient.tsx
  src/pages/ListPage/components/AllRecipient.tsx
  src/pages/ListPage/components/BestRecipient.tsx
  src/pages/ListPage/components/BestRecipientCardList.tsx
  src/pages/ListPage/components/RecipientCard.tsx
  src/pages/ListPage/components/RecipientCardList.tsx
  src/pages/ListPage/components/UI/LoadingSpinner.tsx
  src/pages/ListPage/components/UI/TitleButton.tsx
  tailwind.config.js
Labels: Feat, Design, Fix

#38 [2024.07.19] Emoju 호출 오류 수정 & URL 공유하기 https 환경에서 구동 가능 테스트
  src/pages/HomePage/components/UI/MainContainer.tsx
  src/pages/PostPage/api/getByReactions.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
Labels: Fix, Test, Style

#41 [2024.07.19] CreatePage 화면 구현
  package-lock.json
  package.json
  src/App.tsx
  src/DTO/recipient/Recipient.ts
  src/api/messagePostApi.ts
  src/assets/images/defaultProfileImage.png
  src/pages/MessagePage/MessagePage.tsx
  src/pages/MessagePage/components/DropDown.tsx
  src/pages/MessagePage/components/FontSelectSection.tsx
  src/pages/MessagePage/components/InputProfileSection.tsx
  src/pages/MessagePage/components/InputSenderSection.tsx
  src/pages/MessagePage/components/RelationshipSelectSection.tsx
  src/pages/MessagePage/components/ToastEditor.tsx
  src/pages/MessagePage/hooks/useProfileImage.ts
  src/pages/postCreatePage/PostCreate.tsx
  src/pages/postCreatePage/components/ThemeForm.tsx
  src/pages/postCreatePage/components/ThemePreview.tsx
  src/pages/postCreatePage/components/UI/CloseButton.tsx
Labels: Feat, Design

#44 [2024.07.19] 홈페이지와 post nav 리팩토링 및 Dropdown 파일명 변경
  src/App.tsx
  src/components/Layout/Header.tsx
  src/components/UI/NavButton.tsx
  src/components/UI/NavContainer.tsx
  src/components/UI/NavLogo.tsx
  src/pages/HomePage/assets/images/HomepageAddEmoji.png
  src/pages/HomePage/assets/images/HomepageNotLogin.png
  src/pages/HomePage/components/Layout/HomepageMain.tsx
  src/pages/HomePage/components/UI/BodyContainer.tsx
  src/pages/HomePage/components/UI/MainContainer.tsx
  src/pages/HomePage/components/UI/TitleButton.tsx
  src/pages/HomePage/components/UI/TitleContainer.tsx
  src/pages/HomePage/components/UI/TitleContents.tsx
  src/pages/HomePage/components/UI/TitleHeadContents.tsx
  src/pages/HomePage/components/UI/TitleLine.tsx
  src/pages/HomePage/components/UI/TitlePoint.tsx
  src/pages/MessagePage/components/FontSelectSection.tsx
  src/pages/MessagePage/components/RelationshipSelectSection.tsx
  src/pages/PostPage/components/Layout/PostNav.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/PostNavContainer.tsx
  src/pages/PostPage/components/UI/PostNavTitleContainer.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
Labels: Fix, Rename, Refactor

#49 [2024-07-19] Dropdown 부분 수정
  src/pages/MessagePage/components/Dropdown.tsx
Labels: Fix

#50 [2024.07.19] List 타이틀, 화살표 버튼 스타일 수정
  src/pages/ListPage/components/AllRecipient.tsx
  src/pages/ListPage/components/BestRecipient.tsx
  src/pages/ListPage/components/RecipientCard.tsx
  src/pages/ListPage/components/RecipientCardList.tsx
  src/pages/ListPage/components/UI/Title.tsx
  src/pages/ListPage/components/UI/TitleButton.tsx
Labels: Design

#55 [2024.07.20] List Fix: IOS에서 카드 요소가 카드 밖으로 삐져나오는 현상 수정
  src/pages/ListPage/components/RecipientCard.tsx
Labels: Design, Fix

#56 postCreate: 네임 필드 유효성 검사 추가
  src/pages/postCreatePage/api/ThemeProvider.tsx
  src/pages/postCreatePage/components/ReceiverInput.tsx
  src/pages/postCreatePage/components/ThemePreview.tsx
  src/pages/postCreatePage/components/UI/PreviewButton.tsx
Labels: Feat

#58 postCreate: 폼 버튼 비활성화 기능 보완
  src/pages/postCreatePage/PostCreate.tsx
  src/pages/postCreatePage/components/ReceiverInput.tsx
  src/pages/postCreatePage/constants/propTypes.ts
Labels: Feat

#57 [2024.07.20] feat: 메시지 작성 / 수정 구현
  src/DTO/message/MessageCreate.ts
  src/DTO/message/MessageRetrieve.ts
  src/pages/MessagePage/MessagePage.tsx
  src/pages/MessagePage/components/Dropdown.tsx
  src/pages/MessagePage/components/FontSelectSection.tsx
  src/pages/MessagePage/components/InputProfileSection.tsx
  src/pages/MessagePage/components/InputSenderSection.tsx
  src/pages/MessagePage/components/MessagePageButtons.tsx
  src/pages/MessagePage/components/RelationshipSelectSection.tsx
  src/pages/MessagePage/components/TextEditor.tsx
  src/pages/MessagePage/components/ToastEditor.tsx
  src/pages/PostPage/api/api.tsx
  src/pages/PostPage/components/DeletionConfirmModal.tsx
  src/pages/PostPage/components/LazyLoading.tsx
  src/pages/PostPage/components/MessageCard.tsx
  src/pages/PostPage/components/MessageCardList.tsx
  src/pages/PostPage/components/MessageContent.tsx
  src/pages/PostPage/components/MessageModal.tsx
  src/pages/PostPage/components/MyEditor.tsx
  src/pages/PostPage/components/PlusCard.tsx
  src/pages/PostPage/components/Posts.tsx
  src/pages/PostPage/components/SenderInfo.tsx
  src/pages/PostPage/components/WriteModal.tsx
  src/pages/PostPage/components/WriteModalButtons.tsx
  src/pages/PostPage/components/WriteModalSender.tsx
  src/pages/PostPage/hooks/useInitialMessage.ts
  src/pages/PostPage/hooks/useRequest.ts
  src/pages/PostPage/hooks/useSubmitMethodPicker.ts
  src/pages/PostPage/utils/formatComparedTime.js
Labels: Feat

#59 postCreate: 429 에러, 데이터의 id 값을 전달하지 못하던 에러 해결
  src/pages/postCreatePage/components/ThemeTypeSelection.tsx
  src/pages/postCreatePage/components/UI/PreviewButton.tsx
  src/pages/postCreatePage/components/UI/ThemeTypeButton.tsx
  src/pages/postCreatePage/constants/initial.ts
  src/pages/postCreatePage/hooks/useGetUrls.tsx
  src/pages/postCreatePage/hooks/useSubmitData.tsx
Labels: Design, Fix

#60 [2024.07.21] fix: Post 페이지에서 메세지가 3개까지만 표시되던 버그 수정
  src/pages/PostPage/api/api.tsx
  src/pages/PostPage/components/MessageCard.tsx
  src/pages/PostPage/components/MessageCardList.tsx
  src/pages/PostPage/components/MessageContent.tsx
  src/pages/PostPage/components/Posts.tsx
  src/pages/PostPage/components/WriteModal.tsx
Labels: Feat, Fix

#61 postCreate: 모달창 애니메이션 추가, 버튼 기본 동작 방지
  src/pages/postCreatePage/components/ThemePreview.tsx
  src/pages/postCreatePage/components/ThemeTypeSelection.tsx
  src/pages/postCreatePage/components/UI/ThemeTypeButton.tsx
  tailwind.config.js
Labels: Design, Fix

#64 [2024.07.22] PostNav 반응형 개선 및 Drodown 호출 시 다른 Dropdown 닫기 기능 추가
  src/pages/PostPage/components/Layout/PostNav.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  tailwind.config.js
Labels: Feat, Style

#65 [2024.07.22] Style : PostNav 로딩바 애니메이션 추가
  package-lock.json
  package.json
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/RoundedLoadingBar.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
Labels: Style

#69 [2024.07.22] list 프로필 이미지 호버 이름 띄우는 기능 추가
  src/pages/ListPage/components/RecipientCard.tsx
Labels: Feat

#71 Fix: 카드 슬라이드를 벗어나도 툴팁이 보이게 수정
  src/pages/ListPage/components/RecipientCard.tsx
Labels: Fix

#72 postCreate: 모바일 사이즈, 그리드 디자인 수정
  src/pages/postCreatePage/components/BackgroundColorList.tsx
  src/pages/postCreatePage/components/BackgroundImageList.tsx
Labels: Design

#73 [2024.07.23] 드롭다운 외 영역 클릭시 드롭다운 닫히는 기능 적용 & Message 카운트 수정 & 주석 추가
  src/pages/PostPage/api/getByMessage.tsx
  src/pages/PostPage/components/Layout/PostNav.tsx
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
  src/pages/PostPage/components/UI/ToEmojiCount.tsx
  src/pages/PostPage/components/UI/ToMessageCount.tsx
  src/pages/PostPage/components/UI/ToNameContent.tsx
Labels: Feat, Fix, Comment

#76 Style : PostNav 상단 바 수정
  src/pages/PostPage/components/UI/EmojiAddDropdown.tsx
  src/pages/PostPage/components/UI/EmojiDropdown.tsx
  src/pages/PostPage/components/UI/ShareButton.tsx
Labels: Style

#79 README 작성 완료
  README.md
Labels: Docs
